server:
  port: 8000
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka
management:
  tracing:
    sampling:
      probability: 1.0
spring:
  application:
    name: cambio-service
  jackson:
    time-zone: America/Sao_Paulo
  datasource:
    url: jdbc:postgresql://localhost:5432/cambio-service
    username: ${JAVE_PG_USERNAME}
    password: ${JAVE_PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    url: jdbc:postgresql://localhost:5432/cambio-service
    user: ${JAVE_PG_USERNAME}
    password: ${JAVE_PG_PASSWORD}
    baselineOnMigrate: true
springdoc:
  show-actuator: true
  api-docs:
    path: cambio-service/v3/api-docs
  swagger-ui:
    config-url: /cambio-service/v3/api-docs/swagger-config
    url: /cambio-service/v3/api-docs