version: '3.4'

services:
  naming-server:
    image: henrick182/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      - erudio-network
  zipkin:
    image: openzipkin/zipkin:2.23.8
    ports:
      - 9411:9411
    networks:
      - erudio-network
networks:
  erudio-network:
    driver: bridge