version: '3.4'

services:
  naming-server:
    image: henrick182/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      - erudio-network
  zipkin-server:
    image: openzipkin/zipkin:2.23.8
    ports:
      - 9411:9411
    networks:
      - erudio-network
  api-gateway:
    image: henrick182/api-gateway:0.0.1-SNAPSHOT
    ports:
      - 8765:8765
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans
      MANAGEMENT.TRACING.SAMPLING.PROBABILITY: 1.0
    networks:
      - erudio-network
  cambio-db:
    image: postgres:16
    restart: always
    ports:
      - '5433:5433'
    expose:
      - 5433
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: cambio-service
      PGPORT: 5433
    networks:
      - erudio-network
  book-db:
    image: postgres:16
    restart: always
    ports:
      - '5434:5434'
    expose:
      - 5434
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: book-service
      PGPORT: 5434
    networks:
      - erudio-network
  cambio-service:
    image: henrick182/cambio-service
    restart: always
    build: 
      context: .
      dockerfile: cambio-service/Dockerfile
    ports:
      - 8000:8000
    environment:
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans
      MANAGEMENT.TRACING.SAMPLING.PROBABILITY: 1.0
      SPRING.DATASOURCE.URL: jdbc:postgresql://cambio-db:5433/cambio-service?useSSL=false&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: docker
      SPRING.DATASOURCE.PASSWORD: 12345678  
      SPRING.FLYWAY.URL: jdbc:postgresql://cambio-db:5433/cambio-service?useSSL=false&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: docker
      SPRING.FLYWAY.PASSWORD: 12345678
      SPRING.FLYWAY.BASELINEONMIGRATE: true
    depends_on:
      - naming-server
      - cambio-db
    networks:
      - erudio-network
  book-service:
    image: henrick182/book-service
    restart: always
    build: 
      context: .
      dockerfile: book-service/Dockerfile
    ports:
      - 8100:8100
    environment:
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans
      MANAGEMENT.TRACING.SAMPLING.PROBABILITY: 1.0
      SPRING.DATASOURCE.URL: jdbc:postgresql://book-db:5434/book-service?useSSL=false&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: docker
      SPRING.DATASOURCE.PASSWORD: 12345678  
      SPRING.FLYWAY.URL: jdbc:postgresql://book-db:5434/book-service?useSSL=false&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: docker
      SPRING.FLYWAY.PASSWORD: 12345678
      SPRING.FLYWAY.BASELINEONMIGRATE: true
    depends_on:
      - naming-server
      - book-db
    networks:
      - erudio-network
networks:
  erudio-network:
    driver: bridge