server:
  port: 8100
spring:
  application:
    name: book-service
  jackson:
    time-zone: America/Sao_Paulo
  datasource:
    url: jdbc:postgresql://localhost:5432/book-service
    username: ${JAVE_PG_USERNAME}
    password: ${JAVE_PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    url: jdbc:postgresql://localhost:5432/book-service
    user: ${JAVE_PG_USERNAME}
    password: ${JAVE_PG_PASSWORD}
    baselineOnMigrate: true
