server:
  port: 8100
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka
resilience4j:
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  retry:
    instances:
      default:
        max-attempts: 5
      foo-bar:
        max-attempts: 10
        wait-duration: 1s
        enable-exponential-backoff: true
spring:
  application:
    name: book-service
  jackson:
    time-zone: America/Sao_Paulo
  datasource:
    url: jdbc:postgresql://localhost:5432/book-service
    username: ${JAVE_PG_USERNAME}
    password: ${JAVE_PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    url: jdbc:postgresql://localhost:5432/book-service
    user: ${JAVE_PG_USERNAME}
    password: ${JAVE_PG_PASSWORD}
    baselineOnMigrate: true
springdoc:
  show-actuator: true
  api-docs:
    path: book-service/v3/api-docs
  swagger-ui:
    config-url: /book-service/v3/api-docs/swagger-config
    url: /book-service/v3/api-docs